### ISSUE TITLE
Exception on item pro files (GUI)

### ISSUE THREAD

**Issue by burner1024** [FakelsHub/F2_ProtoManager#9]
Бросает эксепшен когда пытаюсь просмотреть любой итем через гуи. В текстовом формате просматривается нормально. Криттеры в любом формате нормально.

**Comment by FakelsHub** [comment]
кинь любой pro который не открывается.

**Comment by burner1024** [comment]
Да вообще любой. Wine конечно... но дотнет нативный.

**Comment by FakelsHub** [comment]
Поставь виндовс как 2 ос и не мучайся с этим вином.

**Comment by FakelsHub** [comment]
Проверь на какой из старых версий открывается.

**Comment by burner1024** [comment]
Кстати, про старые версии я не подумал.На 1.12 работает, 1.13 нету в релизах, а на 1.14 сломалось.

Но с HiDPI тоже сложности, криттеров показывает нормально, а итемы скукожены.
![Captura de pantalla de 2019-07-08 18-41-14](https://user-images.githubusercontent.com/1279852/60807578-4080a700-a1b0-11e9-8da0-f967178e00fd.png)

**Comment by FakelsHub** [comment]
>.13 нету в релизах

На NMA есть

**Comment by burner1024** [comment]
На NMA скачать что-то не дает старые. На Я.Диске нашел. 1.13 тоже глючит.

**Comment by FakelsHub** [comment]
Понятно посмотрю что там изменилось с 12 на 13

**Comment by FakelsHub** [comment]
[Release.zip](https://github.com/FakelsHub/F2_ProtoManager/files/3387542/Release.zip)
Держи отладочную версию, потом лог пришлешь, а то по логу выше ничего непонятно где произошла ошибка.

**Comment by burner1024** [comment]
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NotImplementedException: The method or operation is not implemented.
   at System.Windows.Forms.UnsafeNativeMethods.ITextRange.ScrollIntoView(Int32 value)
   at System.Windows.Forms.TextBoxBase.ScrollToCaret()
   at Main.PrintLog(String textLog) in D:\My Documents\Projects\ProtoManager.git\ProtoManager\Modules\Main.vb:line 439
   at DatFiles.UnPackFile(String pFile, Boolean сDat) in D:\My Documents\Projects\ProtoManager.git\ProtoManager\Modules\DatFiles.vb:line 113
   at DatFiles.CheckFile(String pFile, Boolean full, Boolean сDat, Boolean unpack) in D:\My Documents\Projects\ProtoManager.git\ProtoManager\Modules\DatFiles.vb:line 65
   at Main.GetItemsData() in D:\My Documents\Projects\ProtoManager.git\ProtoManager\Modules\Main.vb:line 249
   at Main.Create_ItemsForm(Int32 iLST_Index) in D:\My Documents\Projects\ProtoManager.git\ProtoManager\Modules\Main.vb:line 388
   at Main_Form.HToolStripMenuItem_Click_1(Object sender, EventArgs e) in D:\My Documents\Projects\ProtoManager.git\ProtoManager\Main_Form.vb:line 287
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
ProtoManager
    Assembly Version: 1.1.5.0
    Win32 Version: 1.1.5.0
    CodeBase: file:///C:/programs/protomanager/ProtoManager.exe
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

```

**Comment by FakelsHub** [comment]
чето я невижу разницы) что с отладочной инфой что нет.
покажи скрин, на каком этапе ошибка появляется?.

**Comment by FakelsHub** [comment]
не вижу строки

**Comment by FakelsHub** [comment]
покажи лог самой проги там что-то печатается, но ваше ваше вино не может установить позицию каретки.
`System.Windows.Forms.UnsafeNativeMethods.ITextRange.ScrollIntoView(Int32 value)`

**Comment by burner1024** [comment]
Я не вижу лога в директории, где он?

**Comment by FakelsHub** [comment]
[Release.zip](https://github.com/FakelsHub/F2_ProtoManager/files/3387614/Release.zip)
вот без установки каретки попробуй

**Comment by FakelsHub** [comment]
> 
> 
> Я не вижу лога в директории, где он?

там в самой программе снизу печатается лог работы.

**Comment by burner1024** [comment]
Да этот не падает.
![Captura de pantalla de 2019-07-13 01-39-59](https://user-images.githubusercontent.com/1279852/61151097-4e675c80-a50f-11e9-8b1d-0abbe50997d2.png)

В том логе у меня практически ничего нет.
![Captura de pantalla de 2019-07-13 01-40-52](https://user-images.githubusercontent.com/1279852/61151108-52937a00-a50f-11e9-968e-c5d4627a5686.png)

**Comment by FakelsHub** [comment]
Начет маштабирования незнаю в чем проблема, разницы между формой криттеров и предметов никакой нет, щас по dpi  потавлю.

**Comment by FakelsHub** [comment]
[ProtoManager.zip](https://github.com/FakelsHub/F2_ProtoManager/files/3387651/ProtoManager.zip)
вот для контрольной проверки запусти

**Comment by burner1024** [comment]
Да, так отлично работает!
![Captura de pantalla de 2019-07-13 01-47-50](https://user-images.githubusercontent.com/1279852/61151489-465bec80-a510-11e9-97c2-974ea7257467.png)

Можно еще сделать, чтобы ширину столбцов запоминал при выходе? А то каждый раз при запуске приходится их раздвигать:
![Captura de pantalla de 2019-07-13 01-48-55](https://user-images.githubusercontent.com/1279852/61151576-7e632f80-a510-11e9-8c04-606da3eec69b.png)

**Comment by FakelsHub** [comment]
автоматической выравнялка нет, самому геморойно высчитывать ширину текста.

**Comment by FakelsHub** [comment]
Готово.

**Comment by burner1024** [comment]
Спасибо.
